# This is a workflow that runs on multiple OS platforms

name: Multi-OS Installation Script Test

# Controls when the action will run
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    # Define a matrix strategy to run on multiple operating systems
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Download installation script
      run: |
        # Download the installer script to a file
        curl -s https://opendata.xenovate.dpdns.org/docs/rexon/installer.sh > installer.sh
        chmod +x installer.sh
    
    - name: Install on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Create a modified version of the script that doesn't require interactive input
        cat installer.sh | sed 's/read JDK_VERSION/JDK_VERSION=17/' | sed 's/read yn/yn=y/' > non_interactive_installer.sh
        chmod +x non_interactive_installer.sh
        
        # Run the modified script (may require sudo)
        sudo ./non_interactive_installer.sh
        
    - name: Install on macOS
      if: matrix.os == 'macos-latest'
      run: |
        # Create a modified version of the script that doesn't require interactive input
        # macOS sed is different from GNU sed, requires slightly different syntax
        cat installer.sh | sed 's/read JDK_VERSION/JDK_VERSION=17/' | sed 's/read yn/yn="y"/' > non_interactive_installer.sh
        chmod +x non_interactive_installer.sh
        
        # Run the modified script
        ./non_interactive_installer.sh
